
DROP TABLE IF EXISTS STOCKS_TBL ;

CREATE TABLE STOCKS_TBL (
  ID SERIAL PRIMARY KEY ,
  CURRENT_PRICE DOUBLE PRECISION NOT NULL default 0.00, 
  LAST_UPDATE DATE DEFAULT CURRENT_TIMESTAMP , 
  NAME VARCHAR(50) NOT NULL UNIQUE
);
 