
DROP TABLE IF EXISTS STOCKS_TBL ;

CREATE TABLE STOCKS_TBL (
  ID SERIAL PRIMARY KEY ,
  CURRENT_PRICE DOUBLE PRECISION NOT NULL default 0.00, 	 
  NAME VARCHAR(50) NOT NULL UNIQUE,
  LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT NOT NULL
);
 